### ISSUE TITLE
npm install windows-interact fails.

### ISSUE THREAD

**Issue by coreyman** [Arlodotexe/windows-interact#1]
When I try to install this package I get the following -
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/3/2018   2:37 PM                AudioDeviceCmdlets
C:\Users\cmanshack\Documents\macolaAutomation\node_modules\windows-interact\windows-interact.js:675
                                        if (getPowerShellSession(data.child).commandq.length === 0 && getPowerShellSession(data.child).checkingIfDone === false) {
                                                                            ^

TypeError: Cannot read property 'commandq' of undefined
    at checkIfDone (C:\Users\cmanshack\Documents\macolaAutomation\node_modules\windows-interact\windows-interact.js:675:42)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\cmanshack\Documents\macolaAutomation\node_modules\windows-interact\windows-interact.js:703:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package mocha is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

**Comment by Arlodotexe** [comment]
This error message will only effect your ability to manipulate and view info about audio devices. Windows-Interact should otherwise be installed properly.

This has been fixed and will release with the next version of Windows-Interact, which should be in a few days. I will update this thread when an update releases so you can update. Thank you for you help!

**Comment by Arlodotexe** [comment]
The fix for this issue is now live as of version 1.3.0. 

Remember that if you need to use the advanced audio device functionality, Windows Interact needs to be installed using a privileged (admin) terminal at least once.
